export const PLAN_DEFAULTS = {
  free: {
    name: "Free",
    ingredients_limit: 30,
    recipes_limit: 20,
    inventory_limit: 0,
    imports_monthly: 10,
    ai_quota_monthly: 50,
    features: {
      pricing_recs: "basic",
      promotions: false,
      loyalty: false,
      competitor_tracking: false,
      supplier_management: false,
      advanced_menu_optimization: false,
    },
    ai: { max_tokens_per_call: 2000, provider: "GPT-4o-mini" },
  },
  pro: {
    name: "Pro",
    ingredients_limit: 9999,
    recipes_limit: 9999,
    inventory_limit: 50,
    imports_monthly: 9999,
    ai_quota_monthly: 500,
    features: {
      pricing_recs: "full",
      promotions: "standard",
      loyalty: "basic",
      competitor_tracking: false,
      supplier_management: false,
      advanced_menu_optimization: false,
    },
    ai: { max_tokens_per_call: 4000, provider: "GPT-4o" },
  },
  elite: {
    name: "Elite",
    ingredients_limit: 9999,
    recipes_limit: 9999,
    inventory_limit: 9999,
    imports_monthly: 9999,
    ai_quota_monthly: 2000,
    features: {
      pricing_recs: "advanced",
      promotions: "advanced",
      loyalty: "advanced",
      competitor_tracking: true,
      supplier_management: true,
      advanced_menu_optimization: true,
    },
    ai: { max_tokens_per_call: 8000, provider: "GPT-4o" },
  },
} as const;

export type PlanKey = keyof typeof PLAN_DEFAULTS;
